# Generated by Django 5.1.4 on 2025-03-08 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_answer_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='min_score',
            field=models.IntegerField(default=0),
        ),
    ]
