# Generated by Django 5.1.4 on 2025-03-08 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_recommendation_min_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='min_score',
        ),
        migrations.AddField(
            model_name='recommendation',
            name='relevant_questions',
            field=models.ManyToManyField(to='quiz.question'),
        ),
    ]
